### ISSUE TITLE
Running the application

### ISSUE THREAD

**Issue by konate58** [FlorianLoch/prom2mqtt#1]
Hello,
thanks for this good job. How to run application with the configuration file ? 
I have some issues:
nithing in my mqtt server. I use mosquitto

with this config:
mqtt:
  url: "mqtt://localhost:1883"
  username: "ke......"
  password: "M......"
  prometheus:
  -  url: "http://localhost::9095/metrics"
  topics:
    sample-topic:
      name: "prometheus2mqtt"
      labels:
        instance: "raspi"

Regards

**Comment by FlorianLoch** [comment]
Hello,
there are basically two ways to run this:

1. Using the Go toolchain, i.e. calling `go run .` in the directory. 
2. Building a Docker image an running the container. `docker build -t prom2mqtt .` followed by `docker run prom2mqtt` should do the trick. 

The path to the configuration file can be set via the environment variable `PROM2MQTT_CONFIG_PATH`. By default the program will look for the configuration at `./prom2mqtt.config.yaml`. When running with `docker` or `podman` the config file will need to be mounted into the container.

Just for completeness, your configuration should look like this:

```yaml
mqtt:
  url: "mqtt://localhost:1883"
  username: "ke......"
  password: "M......"
prometheus:
  url: "http://localhost:9095/metrics"
topics:
  sample-topic:
    - name: "prometheus2mqtt" # this is the name of your prometheus metric
      labels:
        - name: "instance"
          value: "raspi"
```

Does this help you? :)
